### ISSUE TITLE
Checkout data/core

### ISSUE THREAD

**Issue by soliton-** [czyzby/wesnoth-wml-linter#4]
It'd be useful to checkout at least data/core from the wesnoth repo and add that to the wmllint invocation so it knows about the core macros etc. That way the action user doesn't have to do that. Could perhaps be optional if it's costly.

**Comment by czyzby** [comment]
I'd rather not pull the entire `data/core`, since it has a lot of extra resources (images, music files) that would drastically affect the checkout and build times. Perhaps `data/core/macros/` would be sufficient for `wmllint`? If you can make a list of folders that might be helpful to properly check the WML files, I can try to limit the checkout to the necessary files hopefully without cloning most of the repo.

**Comment by czyzby** [comment]
I've checkout out macros, units and root `cfg` files from the `data/core/` folder. That should address the issues with missing references. Thanks.

**Comment by czyzby** [comment]
I had to include the `data/core` folder in the `wmllint` path for it to pick up all the references correctly, but I managed to make it work by filtering out all reported issues from the Wesnoth core. I ended up addressing this in #5 along with support for some extra parameters and spellchecking.
